vich_uploader:
    db_driver: orm

    mappings:
        Formation:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/../uploads/media'
            delete_on_remove: true
            delete_on_update: false
            inject_on_load: false
            namer:
                service: vich_uploader.namer_property
                options: { property: 'image' }